name: tictac
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 3.1.0
  go_router: ^17.0.1
  rive: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/rive/win.riv